trigger:
  branches:
    include:
    - '*'

schedules:
  - cron: "0 3 * * 0"
    displayName: Weekly Build
    branches:
      include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  TerraformVersion: '1.0.11'
  AzTerraformRegion: 'uksouth'
  AzTerraformResourceGroup: 'fm-geolocationweb-terraform'
  AzTerraformStorageAccount: 'fmgeolocationwebtfstate'
  AzSubscription: 'Personal-Pay-As-You-Go'

stages:
- stage: dependency_check
  jobs:
  - template: dependency-check.yml

- stage: build
  jobs:
  - job: build
    pool:
      vmImage: 'windows-latest'

    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: UseDotNet@2
      inputs:
        version: 6.0.x
        performMultiLevelLookup: true
        includePreviewVersions: true
    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'config'
        nugetConfigPath: './src/nuget.config'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
      displayName: 'dotnet build $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: CopyFiles@2
      displayName: 'Copy web app into artifact staging'
      inputs: 
        SourceFolder: '$(Build.sourcesDirectory)/src/FM.GeoLocation.Web/bin/$(buildConfiguration)/net6.0'
        Contents: '**'
        TargetFolder: '$(Build.artifactStagingDirectory)/webapp'

    - task: CopyFiles@2
      displayName: 'Copy terraform folder into staging directory'
      inputs: 
        SourceFolder: '$(Build.sourcesDirectory)/terraform'
        Contents: '**'
        TargetFolder: '$(Build.artifactStagingDirectory)/terraform'

    - publish: $(Build.artifactStagingDirectory)/terraform
      displayName: Publish terraform artifact
      artifact: terraform

    - publish: '$(Build.artifactStagingDirectory)/webapp'
      displayName: 'Publish website source artifact'
      artifact: webapp

- stage: terraform_state_backend
  jobs:
  - job: create_terraform_backend
    pool:
      vmImage: 'windows-latest'

    steps:
    - checkout: none
      displayName: 'Skip checking out source'

    - task: AzureCLI@1
      displayName: 'Create terraform backend in Azure storage'
      inputs:
        azureSubscription: '$(AzSubscription)'
        scriptLocation: inlineScript
        inlineScript: |
          call az group create --location "$(AzTerraformRegion)" --name "$(AzTerraformResourceGroup)"
          call az storage account create --name "$(AzTerraformStorageAccount)" --resource-group "$(AzTerraformResourceGroup)" --location "$(AzTerraformRegion)" --sku "Standard_LRS"
          call az storage container create --name "terraform" --account-name "$(AzTerraformStorageAccount)"

- template: deploy-application.yml
  parameters:
    environment: 'luna'